# Generated by Django 5.2.7 on 2025-10-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='activity end date'),
        ),
    ]
