# Generated by Django 5.2.7 on 2025-10-09 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_task', to='core.task'),
        ),
    ]
