# Generated by Django 5.2.7 on 2025-10-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shift_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='schedule date')),
                ('start', models.DateTimeField(verbose_name='activity datetime start')),
                ('end', models.DateTimeField(verbose_name='activity datetime end')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daly_schedule', to='core.owner')),
            ],
        ),
    ]
