# Generated by Django 5.2.7 on 2025-10-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='owner',
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='daily_shift', to='core.schedule'),
            preserve_default=False,
        ),
    ]
