# Generated by Django 5.2.7 on 2025-10-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_shift_owner_shift_schedule'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('owner', 'date'), name='unique_schedule_by_owner'),
        ),
    ]
