# Generated by Django 5.2.7 on 2025-10-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schedule_unique_schedule_by_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee', 'shift_date'], name='core_shift_employe_007060_idx'),
        ),
    ]
