# Generated by Django 5.2.7 on 2025-10-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_shift_core_shift_employe_007060_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['schedule', 'start_time'], name='core_shift_schedul_89cd37_idx'),
        ),
    ]
